development:
  cloud_name: gigsite
  api_key: 'asdf'
  api_secret: test
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: gigsite
  api_key: 'asdf'
  api_secret: test
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: gigsite
  api_key: 'asdf'
  api_secret: test
  enhance_image_tag: true
  static_file_support: false